name: Build Docker Image and Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simple-calculation:latest,${{ secrets.DOCKERHUB_USERNAME }}/simple-calculation:${{ github.sha }}

  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs: docker
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update Next.js config for static export
        run: |
          echo "/** @type {import('next').NextConfig} */" > next.config.mjs
          echo "const nextConfig = {" >> next.config.mjs
          echo "  output: 'export'," >> next.config.mjs
          echo "  images: { unoptimized: true }," >> next.config.mjs
          echo "  basePath: process.env.NODE_ENV === 'production' ? '/simple-calculation' : ''," >> next.config.mjs
          echo "};" >> next.config.mjs
          echo "" >> next.config.mjs
          echo "export default nextConfig;" >> next.config.mjs
          cat next.config.mjs
        
      - name: Build
        run: npm run build
        
      - name: List directories
        run: ls -la
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out
